### ISSUE TITLE
Verify email error

### ISSUE THREAD

**Issue by timprint** [percipioglobal/craft-notifications#83]
I have a site that I have recently updates to Craft 3.7.63. The site has been working fine for a couple of years but after the update I am having trouble with front end registrations. It was working OK previously.

In my config I have 'verifyEmailSuccessPath' => 'account/log-in',

Verification emails are sent OK but on clicking the url in the email the user gets an "Error 500" page. The account is verified but they aren't redirected to 'account/log-in'

Hitting the url in the verification email on local I get:

```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: craft\events\UserEvent::userId
```

Stacktrace copied below.

```
yii\base\UnknownPropertyException: Getting unknown property: craft\events\UserEvent::userId in /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php:141
Stack trace:
#0 /var/www/html/notifications/MemberActivated.php(24): yii\base\BaseObject->__get('userId')
#1 /var/www/html/vendor/percipioglobal/craft-notifications/src/services/NotificationsService.php(89): app\notifications\MemberActivated->via()
#2 /var/www/html/vendor/percipioglobal/craft-notifications/src/Notifications.php(97): percipioglobal\notifications\services\NotificationsService->send(Object(app\notifications\MemberActivated))
#3 [internal function]: percipioglobal\notifications\Notifications->percipioglobal\notifications\{closure}(Object(craft\events\UserEvent))
#4 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\UserEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'afterActivateUs...', Object(craft\events\UserEvent))
#6 /var/www/html/vendor/craftcms/cms/src/services/Users.php(698): yii\base\Component->trigger('afterActivateUs...', Object(craft\events\UserEvent))
#7 /var/www/html/vendor/craftcms/cms/src/services/Users.php(737): craft\services\Users->activateUser(Object(craft\elements\User))
#8 /var/www/html/vendor/craftcms/cms/src/controllers/UsersController.php(638): craft\services\Users->verifyEmailForUser(Object(craft\elements\User))
#9 [internal function]: craft\controllers\UsersController->actionVerifyEmail()
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('verify-email', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('users/verify-em...', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction('users/verify-em...', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/html/public_html/index.php(21): yii\base\Application->run()
#18 {main}
```

I first contacted Craft support and they suggested I get in touch with you as it looks like the error is originating from the Notifications plugin

```
#3 [internal function]: percipioglobal\notifications\Notifications->percipioglobal\notifications{closure}(Object(craft\events\UserEvent))
```

Any ideas why this might be or what I could do to try and debug/fix it?

I am on Notifications v 1.2.3

**Comment by cookie10codes** [comment]
hi @timprint,

Apologies for the late reply. Can you send me the MemberActivated php file please?

**Comment by timprint** [comment]
@cookie10codes no problem, I managed to get this fixed myself, I should have updated the ticket.

In MemberActivated php changing
`$user = craft\elements\User::find()->id($this->event->userId)->one();`
to
`$user = craft\elements\User::find()->id($this->event->user->id)->one();`
fixed it.

It's all working OK now.

**Comment by cookie10codes** [comment]
@timprint I’m glad you’ve solved the issue
